#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using BrainDrain.Systems;
using BrainDrain.UI;

namespace BrainDrain.EditorTools
{
    /// <summary>
    /// Builds 6 placeholder ButtonTheme assets (stage 0..5) and wires them into the scene's
    /// UniversalButtonBorderApplier.stageThemes array, proving the theme pipeline end to end
    /// without requiring new art: every placeholder reuses the existing
    /// ButtonBorder_Stage5.png sprite (already generated by ArtExpansionTool) as its border, and
    /// leaves fill/text overrides off so every button keeps its current appearance apart from the
    /// border. Adding a real per-stage look later, or a novelty/seasonal pack, means creating new
    /// ButtonTheme assets and reassigning this array (or calling ApplyOverrideTheme) -- zero code
    /// changes.
    ///
    /// Idempotent: re-running finds and updates existing theme assets/wiring by path/name rather
    /// than duplicating, same pattern as ArtExpansionTool/WeatherSystemWireFix.
    /// </summary>
    public static class ButtonThemeWireFix
    {
        private const string ThemeFolder = "Assets/_Game/ButtonThemes";
        private const string PlaceholderBorderPath = "Assets/_Game/Sprites/UI/Generated/ButtonBorder_Stage5.png";
        private const int StageCount = 6;

        [MenuItem("BrainDrain/Fix Button Theme System")]
        public static void Fix()
        {
            if (EditorToolGuard.BlockedByPlayMode("ButtonThemeWireFix.Fix")) return;

            Sprite placeholderBorder = AssetDatabase.LoadAssetAtPath<Sprite>(PlaceholderBorderPath);
            if (placeholderBorder == null)
            {
                Debug.LogWarning($"[ButtonThemeWireFix] Could not load placeholder border sprite at '{PlaceholderBorderPath}' -- aborting.");
                return;
            }

            Directory.CreateDirectory(ThemeFolder);
            AssetDatabase.Refresh();

            var themes = new ButtonTheme[StageCount];
            for (int i = 0; i < StageCount; i++)
            {
                themes[i] = FindOrCreateTheme(i, placeholderBorder);
            }

            UniversalButtonBorderApplier applier = Object.FindAnyObjectByType<UniversalButtonBorderApplier>(FindObjectsInactive.Include);
            if (applier == null)
            {
                Debug.LogWarning("[ButtonThemeWireFix] No UniversalButtonBorderApplier found in the scene -- theme assets created, but nothing wired. Run ArtExpansionTool's border generator first.");
                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh();
                return;
            }

            AssignArrayField(applier, "stageThemes", themes);
            EditorUtility.SetDirty(applier);
            EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log($"[ButtonThemeWireFix] Done -- {StageCount} placeholder ButtonTheme assets created/updated and wired into UniversalButtonBorderApplier.stageThemes. Save the scene (Ctrl+S) to persist.");
        }

        private static ButtonTheme FindOrCreateTheme(int stageIndex, Sprite placeholderBorder)
        {
            string path = $"{ThemeFolder}/ButtonTheme_Stage{stageIndex}.asset";
            ButtonTheme theme = AssetDatabase.LoadAssetAtPath<ButtonTheme>(path);

            if (theme == null)
            {
                theme = ScriptableObject.CreateInstance<ButtonTheme>();
                AssetDatabase.CreateAsset(theme, path);
            }

            // Placeholder only -- every stage reuses the same existing border art. No fill/text
            // overrides, so buttons keep their current appearance apart from the border. Real
            // per-stage art and any fill/text styling are a separate, later pass.
            theme.borderSprite = placeholderBorder;
            theme.overrideFillColor = false;
            theme.fillSprite = null;
            theme.labelFontMaterial = null;
            theme.overrideTextColor = false;

            EditorUtility.SetDirty(theme);
            return theme;
        }

        /// <summary>Overwrites a serialized array/list field via SerializedObject -- safe regardless of the field's C# access level. Same technique ArtExpansionTool.AssignArrayField uses.</summary>
        private static void AssignArrayField(Component component, string fieldName, Object[] items)
        {
            SerializedObject so = new SerializedObject(component);
            SerializedProperty arrayProp = so.FindProperty(fieldName);
            if (arrayProp == null)
            {
                Debug.LogWarning($"[ButtonThemeWireFix] Could not find serialized field '{fieldName}' on {component.GetType().Name}.");
                return;
            }

            arrayProp.arraySize = items.Length;
            for (int i = 0; i < items.Length; i++)
            {
                arrayProp.GetArrayElementAtIndex(i).objectReferenceValue = items[i];
            }

            so.ApplyModifiedProperties();
        }
    }
}
#endif
